settings:
  name: E-Series
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: E-Series docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Discover E-Series systems
          url: /task-discover-e-series.html
    - title: Manage E-Series systems
      entries:
        - title: View your E-Series systems
          url: /task-view-e-series.html
        - title: Remove a working environment
          url: /task-remove-e-series.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
